name: Update ICS

on:
  schedule:
    - cron: "0 2 * * *"   # run daily at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Sync to latest main and run scraper
        run: |
          # Ensure we're working from the absolute latest main
          git fetch origin main
          git reset --hard origin/main
          # Now generate the ICS file
          python scraper.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add vtc-events.ics
          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Update ICS"
            git push origin main
          else
            echo "No changes detected. Skipping commit."
          fi
